server:
  http_listen_port: 9080
  gprc_list_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ecommerce-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ecommerce-backend
          __path__: /var/log/*.log
